### ISSUE TITLE
Design main docs page

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonarwhal.com#112]
Right now it is a bit empty:
![image](https://cloud.githubusercontent.com/assets/606594/26641610/04d5cb96-45e0-11e7-8840-e7952e6ecad9.png)

**Comment by ststimac** [comment]
Cross posting from the search results page/search page discussion. Proposed layout for the docs landing page:

![screen shot 2017-07-06 at 11 58 59 am](https://user-images.githubusercontent.com/18073131/27928107-c988c7e4-6242-11e7-8b0a-2e98ea76d04c.png)

**Comment by molant** [comment]
@ststimac @qzhou1607 is this done?

**Comment by ststimac** [comment]
This the Docs landing page so if that's merged it should be complete.

**Comment by ststimac** [comment]
Confirmed that this has been merged so I will close. 
Making a minor style edit in a PR to fix an alignment issue.
