### ISSUE TITLE
Style for inactive section titles in ToC

### ISSUE THREAD

**Issue by qzhou1607** [sonarwhal/sonarwhal.com#117]
The original plan was to use black font for the inactive section titles. But now we have the purple toc-arrow icons, so it looks as below:
![toc](https://user-images.githubusercontent.com/20218531/26844087-21e9ada8-4aa7-11e7-8afe-2580348bbe68.PNG)
Btw, I styled the active and inactive titles as using the same color just for now.

**Comment by ststimac** [comment]
We can close this. I updated the TOC section titles and arrows to be black in PR #145, the black arrow doesn't look so strange next to the purple title when the section is "open" or active.
