### ISSUE TITLE
Fix Twitter logo

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal.com#138]
![](https://user-images.githubusercontent.com/1223565/27311320-d770f318-5568-11e7-9f37-d61717538d8e.png)

**Comment by dmethvin** [comment]
Although I've seen people say it shouldn't need to be done, when I run into this I fix it with a `width` and `height` attribute on the `<svg>` or set the width/height in the stylesheet.  The ViewBox size alone doesn't do it.

**Comment by ststimac** [comment]
So I'm in the latest version of Chrome (59) and Edge 41.16227

Everything appears to be appearing correctly for me on Mac and my Surface Book.

**Comment by molant** [comment]
Looking fine now in all my machines :/
