### ISSUE TITLE
Design Updates

### ISSUE THREAD

**Issue by ststimac** [sonarwhal/sonarwhal.com#143]
List of updates to make that are mostly cosmetic. Re-assessing colors used in places since the documentation layout changed slightly (mostly due to content)

- [x] Change Documentation header weight, width, and color
- [x] toc-subsection-title margin-left: change to 0
- [x] toc main categories (formatters, collectors, rules) should be black or the darker grey used, then blue when expanded/active
- [x] update Nellie illustration on home page 
- [x]  Fix footer list item margin on other pages except home
- [x] Change cursor on toc section titles so it looks clickable

**Comment by alrra** [comment]
@ststimac I think this can be closed, right?

**Comment by ststimac** [comment]
@alrra yes
