### ISSUE TITLE
Limit image width

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal.com#153]
See https://sonarwhal.com/docs/user-guide/formatters/index.html

![](https://user-images.githubusercontent.com/1223565/27588902-5f449ae4-5b52-11e7-97f7-e75c0cda7ddd.png)

**Comment by molant** [comment]
@qzhou1607 can you help worth this if @ststimac doesn't have the time?

**Comment by ststimac** [comment]
Can probably work on this later this afternoon. @qzhou1607 I will let you know if I don't get to it.
