### ISSUE TITLE
Make clearer why someone should use sonar

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonarwhal.com#155]
It isn't obvious in the homepage for someone that doesn't know about the project:

https://twitter.com/mgifford/status/879531935898492928

**Comment by molant** [comment]
@alrra, @ststimac can you please work on this?

**Comment by mgifford** [comment]
Thanks!

**Comment by molant** [comment]
Thinking about something like the following in the home page, although I think it is a bit too long. 

> web development is complex: accessibility, security, performance, pwa, browser compatibility... sonar helps you write better code that fits your requirements.

Also not sure about the styles, will rely on @ststimac for this

![image](https://user-images.githubusercontent.com/606594/30233679-ecbf7712-94ab-11e7-96ee-f9328fdecc0b.png)

@sonarwhal/contributors ?

**Comment by qzhou1607** [comment]
It seems that the text part can stretch pretty long on mobile screens if we don't hide it.  What if we have a 'Why Sonar?' item under the 'About'  menu in the navigation bar? Then we will have a whole page to explain why sonar should be used.

**Comment by molant** [comment]
> What if we have a 'Why Sonar?' item under the 'About' menu in the navigation bar? 

We still need to have something on the homepage that explains what it does and why to use it.

**Comment by ststimac** [comment]
Yeah, I'll work on the styling of this today :) @molant I think the copy length will be fine after I reduce the text size and get rid of the all caps.

**Comment by molant** [comment]
This is live now and closed via https://github.com/sonarwhal/sonarwhal.com/pull/206
