### ISSUE TITLE
Make `contributors` page more responsive

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal.com#156]
<img src="https://user-images.githubusercontent.com/1223565/27623197-f2f38f20-5be3-11e7-8c9f-5e881e35443f.png" width=300>

**Comment by molant** [comment]
What's the device and resolution? Looks good on mine:
![img_3556](https://user-images.githubusercontent.com/606594/27628867-a384b402-5bf0-11e7-9f6e-869348cfb60c.PNG)

**Comment by ststimac** [comment]
I think the issue here is that the all-contributors layout we're using generates a table so things aren't as responsive as they could be.

**Comment by molant** [comment]
Do you want to change it to something more responsive?

**Comment by ststimac** [comment]
Can I use HTML instead of markdown to structure the page?

**Comment by molant** [comment]
Yup, we are already using it there so I don't see why not.

**Comment by molant** [comment]
You can also have a new template for this page and just iterate over the list. @qzhou1607 can tell you how to add a new one or help with this.

**Comment by ststimac** [comment]
@qzhou1607 I'll build the structure of the page and then hand it off to you. 

@molant when I add in new names, I assume I find them under sonar contributors, or is it sonarwhal and sonar?

**Comment by molant** [comment]
Let's use both 😊
