### ISSUE TITLE
Consider removing gradient from header

### ISSUE THREAD

**Issue by austinkelleher** [sonarwhal/sonarwhal.com#160]
I personally feel that removing the gradient from the header results in a cleaner look. If you all agree, I can make this change:

Homepage with gradient:

![screen shot 2017-06-29 at 4 20 48 pm](https://user-images.githubusercontent.com/3771924/27708579-6be53876-5ce7-11e7-97d3-3859003cf8f8.png)

Homepage without gradient (I also like how it looks like the sky):

![screen shot 2017-06-29 at 4 19 10 pm](https://user-images.githubusercontent.com/3771924/27708584-725a964c-5ce7-11e7-9f2b-1bb4313b893e.png)

Docs with gradient:

![screen shot 2017-06-29 at 4 19 33 pm](https://user-images.githubusercontent.com/3771924/27708602-7ca34108-5ce7-11e7-9507-87e6f1044fe6.png)

Docs without gradient:

![screen shot 2017-06-29 at 4 20 21 pm](https://user-images.githubusercontent.com/3771924/27708630-94e422f0-5ce7-11e7-8c4c-c45d9441f9d9.png)

**Comment by ststimac** [comment]
The gradient was used to create some depth on the page so everything doesn't feel so flat, so I'd prefer to keep it.

**Comment by austinkelleher** [comment]
I don't have a strong opinion on this either way. I do think that it makes the doc pages in particular cleaner, but I'm fine with closing this.

**Comment by alrra** [comment]
For the docs, I also think it look better.

**Comment by molant** [comment]
The new design doesn't have a gradient. Closing.
