### ISSUE TITLE
Documentation link links to /

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonarwhal.com#161]
It should link to `/docs/`
Current markup is:
```html
<a role="button" href="/" id="docs" aria-haspopup="true" aria-expanded="false" aria-controls="submenu-docs" class="navitem__button expandable">Documentation</a>
```

About button should be similar. Related to https://github.com/sonarwhal/sonarwhal.com/pull/159#discussion_r124929317

**Comment by molant** [comment]
@qzhou1607 I believe this is fixed?

**Comment by qzhou1607** [comment]
@molant Yep.
