### ISSUE TITLE
Document what is happening on the server

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal.com#184]
Document:

- [x] How the content gets updated.
- [x] Let's Encrypt setup.
- [x] Other.

**Comment by molant** [comment]
@alrra at least the first point is yours, right?

**Comment by alrra** [comment]
> at least the first point is yours, right?

If you are referring on how the content gets update here on GitHub, yes. But I was referring on how the content gets updated on the server.

**Comment by molant** [comment]
updated != uploaded 😜
I think we should document both.

**Comment by alrra** [comment]
> I think we should document both.

👍
