### ISSUE TITLE
https://sonarwhal.com/about/code_of_conduct.html => 404

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal.com#192]
https://sonarwhal.com/about/code_of_conduct.html => 404

---

Related: #190, https://github.com/sonarwhal/sonar/pull/450

**Comment by qzhou1607** [comment]
@alrra It looks like we use https://js.foundation/community/code-of-conduct instead now. So it should be fine that https://sonarwhal.com/about/code_of_conduct.html  returns 404?

**Comment by alrra** [comment]
> So it should be fine that https://sonarwhal.com/about/code_of_conduct.html returns 404?

https://sonarwhal.com/about/code_of_conduct.html should redirect to https://js.foundation/community/code-of-conduct.
