### ISSUE TITLE
Adjust nested list line-height

### ISSUE THREAD

**Issue by ststimac** [sonarwhal/sonarwhal.com#193]
Nested ul elements need some space above the first item.

<img width="546" alt="screen shot 2017-08-24 at 1 28 55 pm" src="https://user-images.githubusercontent.com/18073131/29687160-4288499a-88d0-11e7-87fb-66563b8449b8.png">

**Comment by molant** [comment]
@ststimac is this fixed? Trying to find where in the site this content is but I can't find it :/

**Comment by molant** [comment]
Found it: https://sonarwhal.com/docs/developer-guide/rules/index.html

Looks like it still needs some work. Is this going to happen before summit?

**Comment by ststimac** [comment]
@molant yes this will happen before summit. Working on this today.
