### ISSUE TITLE
manifest-is-valid doesn't show up in the list of PWA rules

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonarwhal.com#195]
![image](https://user-images.githubusercontent.com/606594/29693794-7b8a4a2e-88ec-11e7-9dc8-ee0d150d00e5.png)

@alrra @qzhou1607 do you know why?

**Comment by qzhou1607** [comment]
I can't find the documentation for this rule anywhere. @sarvaje helped me to check. It looks like this documentation for this rule was removed in March.

**Comment by molant** [comment]
The commit that removed the file is https://github.com/sonarwhal/sonar/commit/1f09c8994eb091f065e5d2f65c00a0c321e76fb0

I'm looking at the rule and what it checks for isn't very compelling. @alrra do you have any plans on finishing this rule soon? Otherwise I think we should remove it.

**Comment by alrra** [comment]
> I'm looking at the rule and what it checks for isn't very compelling. 

I think it just remained as a leftover.

> do you have any plans on finishing this rule soon? 

Yes. In the next few days, I'm going to work on the PWA related rules.

**Comment by molant** [comment]
It's showing up now!

![image](https://user-images.githubusercontent.com/606594/38566647-053c4f0a-3c99-11e8-9747-6b1443d31ee6.png)
