### ISSUE TITLE
Navigation treeview is above the page content in the mobile view

### ISSUE THREAD

**Issue by qzhou1607** [sonarwhal/sonarwhal.com#197]
Currently the treeview appears above the actual page content in a smaller screen. Is this an intended change ? @ststimac 

It could be an issue in the rule pages since the expanded panel can stretch pretty long before a user can see the page content:

![mobile](https://user-images.githubusercontent.com/20218531/29948230-92592c04-8e62-11e7-818d-816b8890b71a.PNG)

**Comment by ststimac** [comment]
Ah, yes. I made an update after reviewing one of David Storey's accessibility concerns. This was appearing after the content which would make it hard for a user to navigate around. 

For now I will switch it back to the way it was and open a new issue to explore a better solution on mobile.
