### ISSUE TITLE
Design new solution for tree view/TOC on mobile

### ISSUE THREAD

**Issue by ststimac** [sonarwhal/sonarwhal.com#198]
Currently it appears before the content but the tree view can be incredibly long. If it appears after the content, there are a11y concerns about it being used as navigation since the user would have to go through all the content to get to the bottom. 

Will look at different options, either a dropdown or a flyout menu on mobile.

**Comment by ststimac** [comment]
Proposed change for mobile/smaller screens only, add a dropdown nav at the top of the page. We should probably add a 'back to top' button too. 

![mobile-toc-01](https://user-images.githubusercontent.com/18073131/34503678-9fc4d62c-efce-11e7-876f-f6c2d862819b.png)

![mobile-toc-02](https://user-images.githubusercontent.com/18073131/34503679-9fdb1d1a-efce-11e7-9b1c-09081cf267f2.png)

cc: @molant

**Comment by molant** [comment]
> We should probably add a 'back to top' button too.

Yes, the documentation pages can be long.

LGTM!

**Comment by ststimac** [comment]
I'll open an issue for the back to top button if we don't have one already.
