### ISSUE TITLE
Section link icon is on next row

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal.com#200]
https://sonarwhal.com/docs/developer-guide/rules/index.html#evaluatejavascriptinthepagecontext

![](https://user-images.githubusercontent.com/1223565/29997671-03178b64-9022-11e7-8574-a7487fa03bf7.png)

**Comment by molant** [comment]
I think it depends on the resolution?
![img_5796](https://user-images.githubusercontent.com/606594/29997741-1b952cca-8fd0-11e7-9fac-30ea39881bcf.PNG)

**Comment by ststimac** [comment]
What browser are you in? The below screenshots are from Edge. That line of text should be wrapping on larger screen sizes:

![section-link](https://user-images.githubusercontent.com/18073131/30070303-e37da994-9217-11e7-960a-b3f0b6842186.PNG)

Even on smaller ones the icon is in the right place:

![section-link-2](https://user-images.githubusercontent.com/18073131/30070478-67abccc8-9218-11e7-9380-c9bc452ded94.PNG)

**Comment by alrra** [comment]
> What browser are you in? 

Sorry for forgetting to specify that: Firefox on macOS.

**Comment by ststimac** [comment]
Spotted the problem. Missing a position: absolute on the <a> element. 

Can someone check this page in Chrome? None of the section link icons are showing up for me on Windows in Chrome.

**Comment by molant** [comment]
Works on my machine (tm) in the live site:

![image](https://user-images.githubusercontent.com/606594/30073405-800d260e-9222-11e7-90b7-192e14cea895.png)

**Comment by ststimac** [comment]
Now working in Chrome for me. Very strange. I'll make the update so FF displays correctly.

**Comment by qzhou1607** [comment]
It could be caused by the cached page in the service worker. In that case close the tabs/browser and open a new one will fix it (Refresh doesn't work).

> Now working in Chrome for me. Very strange. I'll make the update so FF displays correctly.

**Comment by ststimac** [comment]
@qzhou1607 ah yes. That makes sense. :) Thanks!
