### ISSUE TITLE
Docs page has no title

### ISSUE THREAD

**Issue by willmorgan** [sonarwhal/sonarwhal.com#208]
If I go here, the webpage has no title:

https://sonarwhal.com/docs/

`<!doctype html><html lang="en"><head><meta charset="utf-8"><title></title><meta name="description" content="sonar website">`

**Comment by molant** [comment]
@qzhou1607 can you take care of this?

> sonar documentation

Should be enough.

Thanks @willmorgan!

**Comment by molant** [comment]
Renaming the issues as there are some other issues around titles:

* [ ] https://sonarwhal.com/docs
* [ ] https://sonarwhal.com/about/contributors.html --> should be `Contributors`
* [ ] scanner page
* [ ] scanner results page

Will be nice if we could append `| sonar` to the title for all the subpages.

**Comment by ststimac** [comment]
@molant also Changelog has no title.
