### ISSUE TITLE
Scan Result Scenarios

### ISSUE THREAD

**Issue by ststimac** [sonarwhal/sonarwhal.com#215]
@molant @sarvaje let me know if there is anything I'm missing, any scenario I haven't accounted for. 

User clicks scan button and any of the following scenarios are possible: 

1. Scan & scan timer start. Scan completes successfully. Show 'scan complete' message.

2. Scan & scan timer start. Scan only partially completes. Show 'scan incomplete' message that indicates some results are available but they should try scanning again (link back to scanner in message).

3. Scan is unable to start. Show scan error message and provide link back to scanner. 

4. Scan is placed into queue. Show queue message with permalink letting user know they can come back later using the link to view the results. Option for user to enable push notification?   

Those are the 4 scenarios I have. Let me know if I'm missing anything/if there's anything else that could happen. 

From a UX perspective, I think the Nellie overlay should become it's own page, maybe with some text below Nellie, telling the user what is happening, because then if the scan fails to start, the error page should be it's own page, and not have any of the UI components that are on the results page of a successful scan. And the same with the queue page. I don't want unnecessary clutter on the results page if we're not technically giving the user any results because of a) complete scan failure or b) put into a queue. 

If this all sounds good, I'll start mocking up the queue page, error page, and the updates to the results page to indicate the scan is still in progress and results are still being updated.

**Comment by molant** [comment]
Are you taking into account that results might come in chunks and not at the same time?

**Comment by sarvaje** [comment]
>Scan is placed into queue. Show queue message with permalink letting user know they can come back later using the link to view the results. Option for user to enable push notification?

I think there is another scenario:
5) The user check a permalink and the scan is still in the queue.

**Comment by ststimac** [comment]
@molant yes. But if the scan fails completely there won't be anything to show correct? And if the scan is still in the queue...nothing to show yet, in terms of results, correct?

**Comment by molant** [comment]
>  if the scan fails completely there won't be anything to show correct?

Correct

> if the scan is still in the queue...nothing to show yet, in terms of results, correct?

No results, but maybe something like: "Your request is still in the queue"

**Comment by ststimac** [comment]
Are we going to tell users what number they are in the queue?

**Comment by molant** [comment]
We can tell them how many they were ahead of them when the process started, but unfortunately with the current implementation we cannot tell them how many left they are :(

**Comment by ststimac** [comment]
Ok, we'll leave that info out then.

**Comment by ststimac** [comment]
While the scanner is scanning and compiling results, have some spinners, as each category finishes, the spinner would disappear to be replaced with either a checkmark and success message, or a scan failed message for partial results or the normal list of errors and warnings.

![scan_results_100217-17](https://user-images.githubusercontent.com/18073131/31102747-5d4cc996-a788-11e7-92b5-ec2a1026d4e7.png)


Scenario 1
![scan_results_100217-20](https://user-images.githubusercontent.com/18073131/31102685-19c5bdae-a788-11e7-9d99-c7cca242ca0f.png)

Scenario 2
![scan_results_100217-16](https://user-images.githubusercontent.com/18073131/31102710-3723416e-a788-11e7-9b71-e672a40cb198.png)


Scenario 3
Do we want to direct people to file an issue if they have issues with the scanner? 
![scan_results_100217-19](https://user-images.githubusercontent.com/18073131/31102608-baa4b636-a787-11e7-83ad-baebc3c0b526.png)

Scenario 4 & 5
Need to just slightly modify the message for a return user
![scan_results_100217-18](https://user-images.githubusercontent.com/18073131/31102609-bab4b644-a787-11e7-8845-89d6ade0133e.png)

Let me know if these look good & I'll start building later this week.

**Comment by molant** [comment]
This looks good to me. Also, because some categories might not be visible it will be good to do something with the tiles of the results to indicate the results are in. Just updating the numbers might not be enough (at least in my case).

**Comment by ststimac** [comment]
@molant what if the tiles stay gray until the results are completed, then depending on if there are errors or not, the tile changes to red or green?

**Comment by molant** [comment]
> then depending on if there are errors or not, the tile changes to red or green

👍

**Comment by sarvaje** [comment]
I have a question:
What will see if we have a result for (for example) `interoperability` but there is more results pending for that category? Should we see that result, and at the same time the `compiling error...` message?

**Comment by ststimac** [comment]
@sarvaje yeah, maybe we keep the "compiling errors" message below the results that have already appeared, and then it goes away once everything is completed.

**Comment by ststimac** [comment]
For the sake of time I went with a different design for the loader.

**Comment by qzhou1607** [comment]
@molant @ststimac I have some questions about the "scan failed" message. 
1. Some rules in the same category might return errors/warnings while others fail, putting `scan failed` on the whole category doesn't seem accurate.
2. The way we run the rules in the back end is that we group each 3 rules together (could be cross-category) and run it in one worker. In total there are 7 workers and if one worker fails, the database will refuse to update the result from all the other workers. So it seems not accurate to simply notify the user that all these categories have failed.  @sarvaje  Please correct me if I'm wrong anywhere in the explanation.

What do you think?

**Comment by ststimac** [comment]
So what would a partial scan completed look like? 
It would fail by rule?

**Comment by molant** [comment]
> So what would a partial scan completed look like?

It depends on how we decide to run the rules and that can change at any time. We could decide to run the rules grouped by category, or the rules that take longer separately, etc.

Right now the most likely scenario is that we will have all the rules and `aXe` run separately, so we will have partial results for a11y.

**Comment by qzhou1607** [comment]
@molant @ststimac  So how should I show the `scan failed` message for now? Put it under each rule that failed?

**Comment by qzhou1607** [comment]
@ststimac What's the hex color code of the `green` tile ?
>@molant what if the tiles stay gray until the results are completed, then depending on if there are errors or not, the tile changes to red or green?

**Comment by molant** [comment]
> what if the tiles stay gray until the results are completed, then depending on if there are errors or not, the tile changes to red or green?

Let's change it when we get results and update it. It would be awesome if the green/red changed depend on how many errors/OKs there were and doing it with a transition from the previous color. Although maybe run it first through @ststimac...

**Comment by ststimac** [comment]
For the scan error page, where the scan completely fails, in my mockup I have a line of copy that says "If the issue persists, please file an issue on GitHub."
Should we include that or not?

@qzhou1607 I will get you the hex code of the green tile momentarily. @molant my only issue with the color changing is accessibility but I like the idea. Maybe we can explore at a later time?

**Comment by ststimac** [comment]
@qzhou1607 hex code is #EBF5F1 for the background & we're going to have to change the text color from the purple to green: #006538. 

I'm going to update the scan-results.css & scan-result.hbs file, some of the CSS classes will need to be renamed since they are color specific.

**Comment by ststimac** [comment]
Ignore the portion of my previous comment I just deleted -- no CSS classes need to be added, rule-tile--passed and rule-list--passed are the two classes that just need to be edited :)

**Comment by molant** [comment]
> So how should I show the scan failed message for now? Put it under each rule that failed?

Let's do that for now and we'll see how it looks like in the real later.

**Comment by molant** [comment]
@ststimac I see this in the `Done` column. Can it be closed for reals?

**Comment by ststimac** [comment]
yes
