### ISSUE TITLE
Add opengraph tags to pages

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonarwhal.com#222]
I think it will be nice to add the OG tags to the pages so when people share the urls it looks better.
There should be
* an image: Nellie by default, although it will be nice to be capable of overriding it somehow from the docs.
* title
* description: in the rules' docs maybe the "why is this important" part?

@alrra, @sarvaje @qzhou1607 @ststimac ?

**Comment by sarvaje** [comment]
That would be nice

**Comment by alrra** [comment]
Go for it!
