### ISSUE TITLE
Scanner page scan form styling missing

### ISSUE THREAD

**Issue by ststimac** [sonarwhal/sonarwhal.com#224]
The scanner page styling is incorrect in the scan & scan results PR. It's lost its styling from when I first opened the PR. Need to investigate.

**Comment by molant** [comment]
Look in some of the previous commits of that PR and copy pasta!

**Comment by ststimac** [comment]
@molant it looks like scanner.css isn't being loaded to that page & it looks like some old code was used to write over the new code I had written when you did your layout updates so that I can fix. 

Not sure what I need to do so scanner.css gets loaded.

**Comment by molant** [comment]
@ststimac add it to `/src/hexo/themes/documentation/layout/common.hbs` for now and we will change it if needed.

**Comment by molant** [comment]
This is working now.
