### ISSUE TITLE
Rename `documentation` theme folder to `sonarwhal`

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonarwhal.com#226]
Our theme folder is called `documentation (`/src/hexo/themes/documentation`) which is a bit misleading. We should rename it to `sonarwhal` and update all the references.

**Comment by ZachTRice** [comment]
I have made a pull request for this issue. I believe I followed your contributing documentation as it is stated. I had 2 commits initially but I squashed them into one and included an `Update` tag in my commit message. Let me know if there is anything else you need me to do.
