### ISSUE TITLE
Normalize urls in public site

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonarwhal.com#229]
Right now we have a mix of urls that end on `.html` and not:

* https://sonarwhal.com/docs/developer-guide/connectors/events.html
* https://sonarwhal.com/about/faq.html
* https://sonarwhal.com/docs/developer-guide/
* https://sonarwhal.com/docs/user-guide/

We should normalize them. Probably the ones that do not have `.html` is because they are `index.html` and IIS uses the default one.

**Comment by qzhou1607** [comment]
@molant What is the expected normalized format? Keep the `index.html` for index pages? Or convert the pages ended with `.html` such as `faq.html` to `/faq/` ? If it is the latter one, would we be okay with placing each `about` and `rule` subpage into its own folder?

**Comment by molant** [comment]
Ideally I'd like to remove `.html` from the urls. Not sure if there should be a trailing `/` or not (probably it should work either case)
