### ISSUE TITLE
Add a scanner status section

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonarwhal.com#230]
I think this was lost while we were working on the scanner.
We should have a place in the header where we indicate what's the status of the scanner (`Analyzing`, `Finished`).
Maybe in the top right of the header of the results summary?

![image](https://user-images.githubusercontent.com/606594/31693615-7e4fcee0-b354-11e7-9d03-f00fc1c85369.png)

@ststimac, @qzhou1607 assigning this to you.

**Comment by ststimac** [comment]
We never had a status so this is a new piece to add.
