### ISSUE TITLE
Information close to elapsed time jumps when time changes

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonarwhal.com#231]
1. Go to `/scanner/` and start a new scan
2. Look at `Errors` and `Version`

![image](https://user-images.githubusercontent.com/606594/31693767-51aa5c9c-b355-11e7-857c-9c18cd1e5b8b.png)

**Expected**: Titles to remain in place

**Actual**: Titles slightly move depending on the width of the time (`00:00` and `01:11`, for example) 

@ststimac assigning to you, but if anyone wants to take it before you start feel free!

**Comment by ststimac** [comment]
Making a note: This is probably due to flexbox.

**Comment by ststimac** [comment]
And I may move the permalink to the next line if the links are going to have that many characters.
