### ISSUE TITLE
Scanner should ignore contents of `template`

### ISSUE THREAD

**Issue by aarongustafson** [sonarwhal/sonarwhal.com#241]
See: https://sonarwhal.com/scanner/56409084-80fa-471d-a11e-e535aaa2525b

It flags an image `src` within a `template` element as having the incorrect character encoding header when it is a mustache variable placeholder:

```html
<img class="webmention__author__photo u-photo" src="{{ webmention.author.photo }}" alt="" title="{{ webmention.author.name }}">
```

Suggest it should ignore the contents of `template` *or* only parse linked assets if the value is, in fact, a real URL.

**Comment by alrra** [comment]
@aarongustafson Can you [open this issue in the `sonar` repository](https://github.com/sonarwhal/sonar/issues/new). Thanks!

This repository is for site related issue.

**Comment by aarongustafson** [comment]
Yes, sorry.
