### ISSUE TITLE
'Analyzing' text lost styling

### ISSUE THREAD

**Issue by ststimac** [sonarwhal/sonarwhal.com#245]
There was an id associated with styling that was deleted from the html. Analyzing is now in the wrong location and the animation isn't applied.

![screen shot 2017-10-20 at 8 59 16 am](https://user-images.githubusercontent.com/18073131/31830530-5b207e1a-b575-11e7-9c7f-b9e63730be16.png)

**Comment by molant** [comment]
It should be a class and not an id. There's a conversation in the old PR and @qzhou1607 can tell you more if needed.

**Comment by ststimac** [comment]
It's fine if it's not an id. But whatever was changed broke the positioning and animation.

**Comment by qzhou1607** [comment]
@molant @ststimac For some reason the css and js in production were not updated, even though the code in the `website` branch is correct.

**Comment by ststimac** [comment]
Yeah, I'm noticing that there's CSS missing when I inspect my scan results page on sonarwhal.com while it's analyzing.

**Comment by qzhou1607** [comment]
@molant It looks like the service worker is still running, even after the `hexo-offline` package is removed

**Comment by ststimac** [comment]
This is causing the issue I'm seeing in #246 as well. When I empty cache and hard reload, things look fine.

**Comment by ststimac** [comment]
This is what people are seeing right now on the scan results page on first load...

![screen shot 2017-10-20 at 9 33 01 am](https://user-images.githubusercontent.com/18073131/31831832-b10bef04-b579-11e7-9164-f809ef3fff57.png)

**Comment by ststimac** [comment]
Fixed via #247
