### ISSUE TITLE
Scan result tiles don't collapse evenly

### ISSUE THREAD

**Issue by ststimac** [sonarwhal/sonarwhal.com#246]
Accessibility tile isn't collapsing with the rest of the tiles on smaller screens. Fix layout so it rearranges content down the way the other tiles do.

![screen shot 2017-10-20 at 9 01 46 am](https://user-images.githubusercontent.com/18073131/31830596-93036996-b575-11e7-8fcc-614fdcac27e4.png)

**Comment by qzhou1607** [comment]
This is due to the service worker too

**Comment by ststimac** [comment]
I think there's something else going on here possibly. Again after two hard reloads & cache clearing everything looked fine, but once the scan completed I watched the first tile revert back in size/layout and look like the screenshot above. Need to investigate some more.
