### ISSUE TITLE
Section link icon breaks layout on small viewports 

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal.com#253]
e.g.: 

* Chrome on Android
  
   <img src="https://user-images.githubusercontent.com/1223565/31849534-9f26f22e-b64c-11e7-8bc3-c92baa16fa79.png" width=300>  <img src="https://user-images.githubusercontent.com/1223565/31849518-5351d58a-b64c-11e7-9226-9e94ad8620e5.png" width=300>

* Edge on Android 
  
   <img src="https://user-images.githubusercontent.com/1223565/31849596-67256846-b64d-11e7-9b8c-269523b0dd1f.png" width=300>  <img src="https://user-images.githubusercontent.com/1223565/31849597-675ad44a-b64d-11e7-8f10-49fa8eec84a0.png" width=300>

**Comment by alrra** [comment]
* Edge on Android 
  
   <img src="https://user-images.githubusercontent.com/1223565/31849596-67256846-b64d-11e7-9b8c-269523b0dd1f.png" width=350>
  <img src="https://user-images.githubusercontent.com/1223565/31849597-675ad44a-b64d-11e7-8f10-49fa8eec84a0.png" width=350>

**Comment by ststimac** [comment]
I'm not seeing such a large gap on Chrome on iOS but there is a pixel or two of white still there.
