### ISSUE TITLE
Add ability to open/close all results in the online scanner

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal.com#254]
If the site has a lot of errors it gets annoying to open/expend the result one by one.

**Comment by molant** [comment]
Something similar for adults with lots of results is when you reach the end of a rule and want to collapse it. You need to scroll all the way up and then close it.

Don't know if short cuts could be an option on top of something else?

**Comment by ststimac** [comment]
I'm gleaning from this that @alrra you want an expand all button for each category of results correct? Not just one at the top that opens everything?

**Comment by alrra** [comment]
> want an expand all button for each category of results correct? 

Yes.

**Comment by ststimac** [comment]
<img width="927" alt="screen shot 2018-01-09 at 3 32 55 pm" src="https://user-images.githubusercontent.com/18073131/34748638-67498890-f552-11e7-8182-7f1429c4a585.png">


<img width="936" alt="screen shot 2018-01-09 at 3 30 51 pm" src="https://user-images.githubusercontent.com/18073131/34748581-2172aac2-f552-11e7-903b-8879935425d4.png">

I'm thinking a button either with a light background or a white background. I think an additional solid blue button might get confused with the individual details buttons.

**Comment by alrra** [comment]
> light background 

I personally think the light background (first option) makes it more visible, and thus is better.
