### ISSUE TITLE
Online scanner's Qualys SSL Labs logo link always points to the same site

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal.com#256]
For the _"site doesn't support HTTPS"_ error  the Qualys SSL Labs logo link always points to: https://www.ssllabs.com/ssltest/analyze.html?d=https://ru.hexlet.io. 

---

![](https://user-images.githubusercontent.com/1223565/31905523-22a878fc-b837-11e7-950f-d4c71ca6eef1.png)

---

e.g.:

* https://sonarwhal.com/scanner/12bb99af-fb34-4d9b-b2fd-45caba9e5ba4
* https://sonarwhal.com/scanner/ee156b1f-d60e-44eb-ac27-8271709b9265

**Comment by molant** [comment]
@qzhou1607 can you take a look at this asap, please?
