### ISSUE TITLE
Make scanner indicate scan state using the favicon

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal.com#265]
GitHub recently added something similar, and personally, I think it's a great idea.

![](https://user-images.githubusercontent.com/1223565/31982927-8e8f4802-b963-11e7-84b9-bac38082f782.jpg)

(from https://twitter.com/left_pad/status/922905320543760384?s=03)

**Comment by molant** [comment]
@ststimac want to work on this? I think it would be awesome :)

**Comment by ststimac** [comment]
So I just need to create 3 different favicons to indicate the status of the scan?

**Comment by molant** [comment]
Yup, and then we will update them dynamically.

**Comment by ststimac** [comment]
Do we need .ico and .png formats at 16x16 and 32x32?

**Comment by alrra** [comment]
>  .ico

`.ico` is better for backwards compatibility, and also works everywhere.

**Comment by molant** [comment]
The status indicator is really tiny, especially when side by side with other favicons:

![image](https://user-images.githubusercontent.com/606594/34756493-1b500f12-f580-11e7-9112-0374ad956b36.png)

Maybe we could make Nellie change colors to make it more obivous (or just make the indicator bigger)?

**Comment by ststimac** [comment]
Favicon status icons are still really small. So we should probably do something like the following: 
![screen shot 2018-01-11 at 1 50 38 pm](https://user-images.githubusercontent.com/18073131/34849195-6e4bf058-f6d6-11e7-9875-4ecdd0bcf8fc.png)

**Comment by ststimac** [comment]
Or here is a muted down version 

![screen shot 2018-01-11 at 2 01 58 pm](https://user-images.githubusercontent.com/18073131/34849717-40dd1c3a-f6d8-11e7-9c9d-2574c0bf5914.png)

**Comment by ststimac** [comment]
@molant @alrra

**Comment by molant** [comment]
What about the first option without the dots? If they are going to be of the same color isn't it redundant (and at the favicon resolution will look really tiny)

**Comment by ststimac** [comment]
Yup, we can do that without the dots.

**Comment by molant** [comment]
This has been fixed
