### ISSUE TITLE
Make documentation links from scanner more clear

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal.com#266]
The docs icon doesn't seem to be very clear (see [recent example](https://twitter.com/justmarkup/status/923221586206961664))

![](https://user-images.githubusercontent.com/1223565/32011115-7abd8f92-b9bc-11e7-8697-cad595ba04e0.png)

Maybe we should have text instead of an icon? or is there some other way to make it more clear?

@ststimac, @qzhou1607, @sonarwhal/core  Thoughts?

**Comment by molant** [comment]
Maybe add a text before the image like "Why am I failing this?" that could be hidden in smaller form factors.

**Comment by ststimac** [comment]
I think we could add text next to the icon. Documentation or Docs (that might be too informal).

**Comment by ststimac** [comment]
Any thoughts or suggestions on this solution? :

![screen shot 2017-10-26 at 9 43 18 am](https://user-images.githubusercontent.com/18073131/32065635-29bfb4e6-ba32-11e7-8e85-3899673beeaf.png)

**Comment by alrra** [comment]
> Any thoughts or suggestions on this solution? :

I think that works!
