### ISSUE TITLE
Design About Landing Page

### ISSUE THREAD

**Issue by ststimac** [sonarwhal/sonarwhal.com#268]
Since we've made the headings in the footer all links, About should have a somewhat better looking landing page like docs does. Currently looks like: 

![screen shot 2017-10-26 at 10 13 39 am](https://user-images.githubusercontent.com/18073131/32067014-8c331524-ba36-11e7-991a-05ff01f54181.png)

**Comment by ststimac** [comment]
proposed about landing page design, the only icon I'm iffy on is "contributors" 

thoughts? @molant @alrra 

![about_lp_103117-01](https://user-images.githubusercontent.com/18073131/32251379-013fb690-be4e-11e7-8fc8-def94a1e56d2.png)

**Comment by molant** [comment]
iffy?

I'm ok with your design

**Comment by ststimac** [comment]
yeah, the contributors icon seems off to me but if everyone else is good with it, I'll ship it.

**Comment by ststimac** [comment]
Completed via #285
