### ISSUE TITLE
Rename 'Developer Guide' to 'Contributor Guide'

### ISSUE THREAD

**Issue by rachelnabors** [sonarwhal/sonarwhal.com#272]
Currently we have both "Developer Guide" and "User Guide" in navigation, but it's a little confusing as to what those roles mean (aren't we web _developers_ making products for _users?_). Proposing to clarify by renaming "Developer Guide" to "Contributor Guide" in all instances of the phrase.

**Comment by molant** [comment]
I like it, go for it!
