### ISSUE TITLE
No possibility of refreshing?

### ISSUE THREAD

**Issue by nico3333fr** [sonarwhal/sonarwhal.com#279]
Hi there,

I've tested the tool, it is quite cool, thanks for it. https://sonarwhal.com/scanner/3837003b-b4f4-4e26-a006-abe8a0fd0115

Question: I've fixed several issues on this website, and would like to see if Sonar is okay with it. I can't force rescanning the URL to see the difference. Could you add a button "refresh" or "scan again" to allow doing it?

(a temporary workaround is to add a querystring to the URL)

Thanks,
Nicolas

**Comment by sarvaje** [comment]
Hi @nico3333fr,
The scanner has a cache for 15 minutes, so you just need to wait a little bit and then run the scanner again for the same url.

Thanks!

**Comment by molant** [comment]
@nico3333fr while we are always going to cache results for a few minutes (we expect some popular websites to be requested fairly often, for example), the time could change in the future depending on capacity, resources, etc. What do you think will be a good value?

Also, if you need more flexibility right now, the CLI is the way to go.

**Comment by nico3333fr** [comment]
@molant @sarvaje thanks for answering so quickly. 👍 

In fact, it depends on the server charge: maybe keeping a more longer cache while enabling rescan could be an option if people don't abuse of the rescan option, the way you did it is another option... 👍
