### ISSUE TITLE
FAQ & Governance pages have no breadcrumbs

### ISSUE THREAD

**Issue by ststimac** [sonarwhal/sonarwhal.com#284]
Need to add breadcrumbs to the FAQ & Governance pages.

**Comment by ststimac** [comment]
@qzhou1607 are the FAQ & Governance pages being pulled in through markdown? What's the best way to add breadcrumbs to these two pages?

**Comment by qzhou1607** [comment]
@ststimac Yes they are pulled from the markdown files. You can add the breadcrumbs in the `about.hbs`, which is shared between all pages under `about`. Then we should be able to have breadcrumbs all in one place throughout all of the pages.

**Comment by ststimac** [comment]
Closing as this ended up being fixed in #285
