### ISSUE TITLE
 Scanned URL breaks layout on small viewports

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal.com#286]
Scanned URL:  https://sonarwhal.com/scanner/f32ced4f-df43-42a9-bdb5-6ae7ae7a4fcf

e.g. Edge on Android 

<img src="https://user-images.githubusercontent.com/1223565/32307154-ba7763ee-bf87-11e7-920c-b2197aa8b313.png" width=350>

**Comment by molant** [comment]
@ststimac want to take a look?

**Comment by TejasQ** [comment]
On it.

**Comment by TejasQ** [comment]
🎉

**Comment by alrra** [comment]
@TejasQ Congrats on your first contribution to a sonar project! 🎉
