### ISSUE TITLE
Add companies logos that participate in sonar to website

### ISSUE THREAD

**Issue by ststimac** [sonarwhal/sonarwhal.com#29]
We need a 'sponsored by' section on the homepage right @molant? 

Will also eventually need to add a 'companies using sonar' section too.

**Comment by ststimac** [comment]
@kborchers I'm adding logos to the website. Is there a version of the JS Foundation where "Foundation" is in white?

**Comment by ststimac** [comment]
@patrick-steele-idem marko.js is one of the logos I'm adding to the sonar website. Is there a version I can use where the text "marko" is in white? I found the branding repo https://github.com/marko-js/branding but didn't see any versions like what I'm looking for and wanted to check before I altered the text color in the logo.

**Comment by molant** [comment]
Closing this issue as we will only have logos for the tools and services in the scanner results.
