### ISSUE TITLE
Make sure only `/scanner/` is used

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonarwhal.com#293]
Right now we have `/scanner` and `/scanner/`. We should only have `/scanner/`.

**Comment by sarvaje** [comment]
I think this is already done in `sonarwhal.com`, I'm going to fix a link in the sonarwhal documentation.

**Comment by molant** [comment]
In the analytics I can still see a few instances of `/scanner/` thought. It could be just people hitting that url directly from links so maybe we should have a redirect in place for it as well.
