### ISSUE TITLE
Make links to "more information" in Vulnerable JS audit clickable

### ISSUE THREAD

**Issue by tkadlec** [sonarwhal/sonarwhal.com#295]
Currently, when the scanner finds a vulnerable JS library, it provides a description that says to see the url for more information (for example: See https://snyk.io/vuln/npm:jquery for more information"), but that URL is not clickable.

Would love to make this easier for people to click-through and get remediation information.

**Comment by molant** [comment]
We can probably solve this by creating a new handlebars helper that automatically ads a link if it detects one in the text and then use it in the template. Maybe it will be interesting to add a campaign parameter so you know it's coming from the online scanner?

Helpers are registered in https://github.com/sonarwhal/sonarwhal.com/blob/master/src/hexo/themes/sonarwhal/helper/index.js
and we should use it when passing `{{message}}` in https://github.com/sonarwhal/sonarwhal.com/blob/2fa54cf75b9cac44ade63bd3523fa095c3b54774/src/hexo/themes/sonarwhal/layout/partials/scan-result-item.hbs#L14

Templates and helpers are now shared in between the client and the server so this should be relatively easy. The most complicated part should be running the online-service locally.

@tkadlec if you want to give it a try we can help you with the local set up of the online scanner (shouldn't be too complicated, but you'll need to have a local mongodb).

**Comment by tkadlec** [comment]
Happy to help out! I think I may just need a bit of direction around getting the online-service up and running (namely this bit https://github.com/sonarwhal/online-service/#configuration).

**Comment by tkadlec** [comment]
Thanks!
