### ISSUE TITLE
Create a YouTube channel 

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal.com#300]
- [x] Create a YouTube channel.
- [x] Upload @molant's video.
- [x] Create playlist.

**Comment by molant** [comment]
Already done most of that the other day: https://www.youtube.com/channel/UCmfwMFhIyKtUPKmHszZlq6g,

I'm using the sonarwhal.com account if you want to change things.

**Comment by alrra** [comment]
> Already done most of that the other day

🎉

**Comment by alrra** [comment]
> Create playlist.

@molant [Done](https://www.youtube.com/playlist?list=PLTeNUX-2H4-HYdX4MZXBQaaSUnXbe40V1). We can add more as we have them.
