### ISSUE TITLE
Add link in results to show the used configuration when scanning a URL

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonarwhal.com#309]
Right now the online scanner is using the default browserlist configuration: `> 1%, last 2 versions, Firefox ESR`.

After the discussion in https://github.com/sonarwhal/sonarwhal/issues/666 maybe it's worth thinking about tweaking that configuration, at least while we implement the custom configuration.

The idea will be to remove support for old browsers so rules like `X-UA-Compatible` recommend more up to date practices.

Even though this is a small change, I think it is worth discussing and make sure we are all in the same page. @sonarwhal/contributors, @laukstein what do you think?

**Comment by alrra** [comment]
> The idea will be to remove support for old browsers so rules like X-UA-Compatible recommend more up to date practices.

:+1+

**Comment by laukstein** [comment]
@molant `> 1%, last 2 versions, Firefox ESR` http://browserl.ist/?q=%3E+1%25%2C+last+2+versions%2C+Firefox+ESR
returns old browsers even with 0% usage, IE10 with usage 0.15% . Perhaps you expect more than 1% usage and the configuration needs to be changed, or it is a bug in https://github.com/ai/browserslist ?

**Comment by laukstein** [comment]
@alrra, `X-UA-Compatible` is relevant only till IE10 and IE10 usage is 0.15%.

**Comment by alrra** [comment]
> returns old browsers even with 0% usage, 

@laukstein That is because of `last 2 versions`, part which, as this issue suggests, we intend to remove from the **online scanner** until the scanner allows users to provide their own configurations.

---

Note: Below by `sonarwhal` I am referring to the CLI, not the [online scanner](https://sonarwhal.com/scanner/).

> X-UA-Compatible is relevant only till IE10 

Again, we know that, and we even [clearly specify it in the rule's documentation](https://sonarwhal.com/docs/user-guide/rules/highest-available-document-mode/#whyisthisimportant).

> and IE10 usage is 0.15%.

[`caniuse` desktop data comes from StatCounter's GlobalStats](https://caniuse.com/usage-table), other sources may provide other percentages. In general, users should look at their own site's statistics, and make decisions based on that (e.g.: some sites may get accessed mostly from mobile devices, others may get a lot of traffic from older browsers, etc.).

The idea with `sonarwhal` is to suggest whatever is best for the [user's needs](https://sonarwhal.com/docs/user-guide/#browserconfiguration), but for that the user has to provide `sonarwhal` with some information (e.g.: the support matrix).

Note: If no configuration file is provided, `sonarwhal` will ask the user, among other,  to specify the support matrix, and it will only go with the defaults if the user specifically chooses to.

![](https://user-images.githubusercontent.com/1223565/33082220-15dd98da-ce91-11e7-9b00-b622f6edd3ed.png)

---

Regarding `browserlist`'s defaults, if you think, in general (independent of `sonarwhal`) they should be different, then you should open an issue in their repository. 

---

I hope this clarifies things.

**Comment by molant** [comment]
The easiest path will probably be to use [`> 1%, last 2 versions, Firefox ESR, not ie < 11`](http://browserl.ist/?q=%3E+1%25%2C+last+2+versions%2C+Firefox+ESR%2C+not+ie+%3C+11)

We should also update our documentation to point to the results of the default query.

**Comment by alrra** [comment]
> `> 1%, last 2 versions, Firefox ESR, not ie < 11`

Go for it.

**Comment by laukstein** [comment]
It still lists outdated browsers and with 0% usage. Why not simply `> 1%`?

**Comment by molant** [comment]
`> 1%` will remove modern browsers that haven't been made to the stats like Chrome 62:
![image](https://user-images.githubusercontent.com/606594/33144086-c3396088-cf70-11e7-99e2-387b6559234e.png) and most of the conditional code we have is for old versions of desktop IE.

**Comment by laukstein** [comment]
@molant then you want to use [`> 1%, last 1 version`](http://browserl.ist/?q=%3E+1%25%2C+last+1+version)

Here is `> 1%, last 1 version` vs `> 1%, last 2 versions, Firefox ESR, not ie < 11` difference:

- Chrome for Android 62 (27.78% global usage)
- UC Browser for Android 11.4 (8.10% global usage)
- Chrome 62 (0.89% global usage)
- Chrome 61 (22.19% global usage)
- Chrome 60 (1.15% global usage)
- Edge 16 (0.04% global usage)
- Edge 15 (1.62% global usage)
- Firefox 57 (0.12% global usage)
- Firefox 56 (3.46% global usage)
- ~Firefox 52 (0.50% global usage)~
- IE 11 (3.22% global usage)
- IE Mobile 11 (0.25% global usage)
- ~IE Mobile 10 (0.05% global usage)~
- iOS Safari 11 (5.30% global usage)
- iOS Safari 10.3 (3.60% global usage)
- Opera Mini all (2.63% global usage)
- Opera 48 (0.71% global usage)
- ~Opera 47 (0.07% global usage)~
- Safari 11 (1.21% global usage)
- ~Safari 10.1 (0.63% global usage)~
- Samsung Internet 5 (2.30% global usage)
- Samsung Internet 4 (1.36% global usage)

**Comment by molant** [comment]
That could be an option. Not a huge fan of tweaking the `browserlist` defaults but...

We need to add a section with the online configuration (and link to it), preferably in a place where it can be edited without commits so people know what we are testing for. Maybe a gist we link from the scanner page? @alrra, @sarvaje, @ststimac ?

**Comment by molant** [comment]
Another thing we could update is the [Apple Touch icon `error` to `warning`](https://github.com/sonarwhal/sonarwhal/issues/661#issuecomment-347179970)

**Comment by sarvaje** [comment]
@molant just to be sure, the changes are:
* [ ] Change apple touch rule severity to `warning`
* [ ] Change browserlist to `> 1%, last 2 versions, Firefox ESR, not ie < 11`

**Comment by laukstein** [comment]
@sarvaje see my above comment. I think we need to use `> 1%, last 1 version`.

**Comment by molant** [comment]
It should be 
* [ ] Change apple touch rule severity to `warning`
* [ ] Change browserlist to `> 1%, last 1 version`

as @laukstein says. @poshaughnessy, @sonarwhal/core any other changes we should do?

**Comment by sarvaje** [comment]
ok!

**Comment by sarvaje** [comment]
Changes done!

**Comment by alrra** [comment]
> Changes done!

We should also publish the configs somewhere on GitHub? Maybe the `README.md` of this repository? (Cc @sonarwhal/core)

**Comment by laukstein** [comment]
@sarvaje this change has been released without uprising the version. Now I see the same version 0.16.0 old scan result with `x-ua-compatible` warning and new scan without it...

**Comment by molant** [comment]
Because the sonarwhal version the online scanner is using hasn't change, just the configuration.

That's part of why we should publish the used configuration somewhere that we've been mentioning in this thread. Maybe we should have something next to the version in the results that points to it and use the config id? Thoughts @ststimac?

@sarvaje what about enabling a new endpoint /scanner/config/configId that shows the content of that configuration?
Can't remember if we are storing the configuration for each scan but if not we should start doing it. That way we avoid having to update the config in multiple places.

**Comment by sarvaje** [comment]
>@sarvaje what about enabling a new endpoint /scanner/config/configId that shows the content of that configuration?

I like the idea.

**Comment by molant** [comment]
I've quickly chat with @sarvaje about this. Plan is:
- new endpoint to expose the used config for that run. We are storing that directly in the results. This is good because we will not have to do anything in the future for custom configs 😊
- add a link in the results to see this configuration. @ststimac we'll need your help to make it pretty

**Comment by molant** [comment]
Updated the title of the issue and assigned it to @sarvaje and @ststimac.

@ststimac if you have questions we can talk on Monday.

**Comment by ststimac** [comment]
@molant yeah, let's chat today.

**Comment by molant** [comment]
> let's chat today.

Done, @ststimac will add a link to the new endpoint in the results page that will say "Used configuration" or something similar.

**Comment by alrra** [comment]
> add a link in the results to see this configuration

That change is now live (for example, see: https://sonarwhal.com/scanner/7a2b2978-b84f-4620-85fb-11f78fb3a45).

![](https://user-images.githubusercontent.com/1223565/33859971-5a95b0e8-de8b-11e7-8c16-62a88c278dc3.png)

**Comment by ststimac** [comment]
@alrra one of the lines of CSS isn't being updated. Is that due to service worker? (the update to flex-start)

**Comment by ststimac** [comment]
@alrra ignore that comment, the wrong line of CSS got updated.

**Comment by laukstein** [comment]
@alrra https://sonarwhal.com/scanner/7a2b2978-b84f-4620-85fb-11f78fb3a45 show error page

![grabilla g11760](https://user-images.githubusercontent.com/183966/33900993-103721b4-df79-11e7-85fc-fb969d325e85.png)

**Comment by alrra** [comment]
> @alrra https://sonarwhal.com/scanner/7a2b2978-b84f-4620-85fb-11f78fb3a45 show error page

Yes, the URL was missing a digit, sorry about that, here is the correct link:

https://sonarwhal.com/scanner/7a2b2978-b84f-4620-85fb-11f78fb3a453

**Comment by laukstein** [comment]
@alrra Can you apply pretty-print formatting for JSON files?
The JSON file has Array with 3 Objects containing bunch of properties like `rules` and `browserslist`, etc. Why?
I think we stil don't have an option to add a custom configuration, before running scan, right?
