### ISSUE TITLE
Close icon in details button is too close compared to open 

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonarwhal.com#313]
Open:
![image](https://user-images.githubusercontent.com/606594/33347121-a7d3aae4-d446-11e7-8bcd-16853748dd33.png)

Close:
![image](https://user-images.githubusercontent.com/606594/33347098-93d352b0-d446-11e7-9be1-494f5624b3fb.png)

**Comment by ststimac** [comment]
What browser is this?

**Comment by molant** [comment]
Happening with Chrome and Edge on Windows. I think that also Safari on iOS IIRC.
