### ISSUE TITLE
List of rules is cut with the footer

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonarwhal.com#317]
![image](https://user-images.githubusercontent.com/606594/33352311-1efe4f5a-d45d-11e7-8d19-d12c7a1901a6.png)

Happens on Edge and Chrome.  Example URL: https://sonarwhal.com/docs/user-guide/rules/no-vulnerable-javascript-libraries/

**Comment by ststimac** [comment]
Only happening on Windows in all browsers. Displaying fine on Mac. I'm running all the same browser versions.

**Comment by gregwhitworth** [comment]
I'm able to repro this in Safari on MacOS: 
![image](https://user-images.githubusercontent.com/865244/33394574-9eee911c-d4f7-11e7-9ead-4d15546930fe.png)

**Comment by molant** [comment]
So it looks like a problem with the screen resolution then @ststimac

**Comment by ststimac** [comment]
Thanks Greg. I'm looking into this today.

**Comment by ststimac** [comment]
Yup, I think it's something with the floats. Makes my job easier :)
