### ISSUE TITLE
CloudFlare's mandatory __cfduid cookie should not penalize site

### ISSUE THREAD

**Issue by laukstein** [sonarwhal/sonarwhal.com#318]
Fallow Mozilla steps https://github.com/mozilla/http-observatory/issues/121 and skip validation fort CloudFlare's `__cfduid` cookie

![grabilla em7172](https://user-images.githubusercontent.com/183966/33393385-b6e2f8c6-d547-11e7-94cf-f37613d95bfc.png)

**Comment by alrra** [comment]
@laukstein Care to open this issue in the [`sonarwhal`](https://github.com/sonarwhal/sonarwhal ) repository? Thanks!

---

Note: This repository is for site specific problems.

**Comment by molant** [comment]
But this will go into the ignored urls config for the online scanner so it should go here?

**Comment by alrra** [comment]
> But this will go into the ignored urls config 

Ignoring URLs won't solve much here, as this is about cookies. If we decided to go with this, we need to make some changes to the [`validate-set-cookie-header`](https://github.com/sonarwhal/sonarwhal/blob/8f97e557a1783ba47b56360b3a61d107f63feb5e/src/lib/rules/validate-set-cookie-header/validate-set-cookie-header.ts) rule.

**Comment by laukstein** [comment]
Is moved to https://github.com/sonarwhal/sonarwhal/issues/681

**Comment by alrra** [comment]
Thanks, @laukstein!
