### ISSUE TITLE
Add 'back to top' button on documentation pages

### ISSUE THREAD

**Issue by ststimac** [sonarwhal/sonarwhal.com#343]
Pages can be long, especially on mobile. Design & implement a back to top button.

**Comment by ststimac** [comment]
back to top button mock ups:

![back to top button_artboard 2](https://user-images.githubusercontent.com/18073131/34688359-b3ad74a4-f466-11e7-8085-9e645eeb6a1e.png)
![back to top button-01](https://user-images.githubusercontent.com/18073131/34688360-b3d59f42-f466-11e7-825b-e85e2ae18c9d.png)

**Comment by molant** [comment]
There's code in Edgeportal we can reuse for the JS part if needed.

**Comment by ststimac** [comment]
oh excellent. yes, we will probably need that, as we'll want this to appear once the user is so far down the page.

**Comment by ststimac** [comment]
I am going to need someone to make a slight edit to the javascript I think. The back to top button disappears on smaller screens/mobile.
