### ISSUE TITLE
`<details>`'s non-code content is not displayed correctly on the site

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal.com#367]
| [GitHub](https://github.com/sonarwhal/sonarwhal/blob/437f5d8a484e1ee2e62fae059fb38a03f33fae0f/docs/user-guide/rules/http-compression.md#how-to-configure-the-server-to-pass-this-rule) | [Site](https://sonarwhal.com/docs/user-guide/rules/http-compression/#howtoconfiguretheservertopassthisrule) |
|:---:|:---:|
|  ![](https://user-images.githubusercontent.com/1223565/35254117-bb5ed0fc-ff9d-11e7-86c5-efaf9b0338b9.png) | ![](https://user-images.githubusercontent.com/1223565/35254163-ee6b345e-ff9d-11e7-9082-3b995789a273.png) |

**Comment by alrra** [comment]
Note: I'm referring to the non-code content

**Comment by molant** [comment]
If we enable the `breaks` option of marked we get a slightly better result:

| Live version| breaks enabled | 
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/606594/35352997-9e3866a6-00fa-11e8-8240-0c25f9b2b01c.png) | ![image](https://user-images.githubusercontent.com/606594/35353067-d9b41888-00fa-11e8-84bf-85ca8678b5f8.png) |

**Comment by molant** [comment]
I've been hacking `hexo-rendered-marked` to use `remarkable` instead of marked and things seem to work ok. Unless we want to figure out what's going on with `marked` I think this is our best bet.

Also we might have to write the `html` parts in a particular way. E.g.:

```html
<details><summary>How to configure Apache</summary>

<div>
Apache can be configured to add or remove the `X-UA-Compatible`
header using the [`Header` directive][header directive].
```
