### ISSUE TITLE
Top button link doesn't have enought contrast when it's already visited

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonarwhal.com#369]
1. Go to any documentation page
1. Scroll enough to show the "Top" button
1. Click on the button
1. Scroll again

You will see something like the following:

![image](https://user-images.githubusercontent.com/606594/35314910-19e80748-007e-11e8-820f-0c8b6b230a3b.png)

For reference, the non-visited version looks like:

![image](https://user-images.githubusercontent.com/606594/35314946-586cb7de-007e-11e8-93bf-2ba438c0e1a6.png)

**Comment by ststimac** [comment]
Yup, definitely not supposed to be doing that. Must be pulling in some <a> styling from another stylesheet.
