### ISSUE TITLE
Fix redirects for URLs without a tailing `/`

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal.com#393]
Currently if the rule URL does not contain a tailing `/` it ends up in a 404

e.g.: https://sonarwhal.com/docs/user-guide/rules/rule-meta-viewport => 404

**Comment by alrra** [comment]
I reverted the change from https://github.com/sonarwhal/sonarwhal.com/pull/420, as made the site do weird things (such as redirect [this url](https://sonarwhal.com/scanner/1b94783c-02dd-4ffb-a57e-0ee408d18340/) to [this one](https://sonarwhal.com/scanner/1b94783c-02dd-4ffb-a57e-0ee408d18340/1b94783c-02dd-4ffb-a57e-0ee408d18340/)).

**Comment by molant** [comment]
Where there any other issues or just the scanner results?

**Comment by alrra** [comment]
> Where there any other issues or just the scanner results?

Mostly recursive redirects such as the one from the above example.

**Comment by alrra** [comment]
@molant I reverted the changes again as the same problem appeared. :(

**Comment by molant** [comment]
Was it failing with the scan results or another url?

**Comment by alrra** [comment]
> Was it failing with the scan results

With the scan result.
