### ISSUE TITLE
Scan status favicons are not consistent

### ISSUE THREAD

**Issue by ststimac** [sonarwhal/sonarwhal.com#399]
When my scan was placed into the queue I got the yellow Nellie favicon but upon completion of the scan, I got the purple Nellie with a small X. Shouldn't it be the green Nellie? 

<img width="250" alt="screen shot 2018-02-22 at 1 17 58 pm" src="https://user-images.githubusercontent.com/18073131/36564764-4149f9c4-17d3-11e8-9c98-2dfbf18702b2.png">

Also, I would expect the favicon to be green even if the scan completed and there were errors. I would expect the red Nellie if the scan had in anyway failed. When I initially looked at the scan tab, because I had another tab open, I thought the scan had actually failed when I saw the red x. 

So there's two things: 

1) need to update the favicon so it's one of the full color favicons that we initially landed on
2) minor user experience detail but the favicon should show green if the scan is completed, regardless of errors, and should show red if the scan has actually failed.

**Comment by molant** [comment]
Don't know why you are still getting the old style, but I think the current output is the right one:

* yellow --> Scanning
* red --> site has errors
* green --> site doesn't have any errors

This is what I see on my laptop:

![image](https://user-images.githubusercontent.com/606594/36992658-750219c8-2060-11e8-895b-5dd2aa5af30d.png)
