### ISSUE TITLE
Design icon for "Development" rules

### ISSUE THREAD

**Issue by ststimac** [sonarwhal/sonarwhal.com#402]
@molant if the name of this category of rules changes let me know, this is for the new category discussed in #391 that will have lots of rules.

**Comment by ststimac** [comment]
Preferences for the icon for the "Development" rules? @molant @alrra @sarvaje 

![dev-icons_dev 1](https://user-images.githubusercontent.com/18073131/37736332-e55c8762-2d0d-11e8-8946-7a36054823a2.png)
![dev-icons_dev 2](https://user-images.githubusercontent.com/18073131/37736333-e577c040-2d0d-11e8-8dc4-8784dd24f400.png)

**Comment by molant** [comment]
I can't decide 🤔
We can probably ask around the office see what they think.

**Comment by sarvaje** [comment]
I prefer the first one, is like more development. The second one for my is more like settings.

**Comment by molant** [comment]
This was closed via https://github.com/sonarwhal/sonarwhal.com/commit/6e967f65ba6b92577cdf4d12446ef7ca5959ae5c
