### ISSUE TITLE
Table format doesn't look right

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonarwhal.com#404]
Go to https://sonarwhal.com/docs/user-guide/rules/rule-performance-budget/#can-the-rule-be-configured

This is how it looks in Edge:

![image](https://user-images.githubusercontent.com/606594/37165571-d549dc1e-22b1-11e8-9a83-a4dd1512edbc.png)

**Comment by ststimac** [comment]
Looks like there are styles missing from the CSS.
