### ISSUE TITLE
content-type: errors are flagging false postive when type is just specified after src attribute

### ISSUE THREAD

**Issue by mikerg87** [sonarwhal/sonarwhal.com#411]
script tags with type specified after src is being flagged as non-compliant.
understanding is that tag attributes can be in any order

example site: https://zebu.io

"<script src="js/scrolling-nav.js" type="text/javascript"></script>"

**Comment by alrra** [comment]
> "<script src="js/scrolling-nav.js" type="text/javascript"></script>"

@mikerg87 The errors are related to the media type of the response (HTTP headers).

See: https://sonarwhal.com/docs/user-guide/rules/rule-content-type/

e.g.:

![](https://user-images.githubusercontent.com/1223565/37724711-9dc925e6-2cee-11e8-803a-d45b2eacae73.png)
