### ISSUE TITLE
Sidebar rule menu items are not rendered consistently

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal.com#416]
We now have 3 different ways of displaying things:

<img width="318" src="https://user-images.githubusercontent.com/1223565/38585439-bcc93ae0-3cce-11e8-9042-f61f7595510e.png">

**Comment by sarvaje** [comment]
This is something that needs to be fix in sonarwhal. I have already opened the issue [here](https://github.com/sonarwhal/sonarwhal/issues/1062)

**Comment by molant** [comment]
Closed via https://github.com/sonarwhal/sonarwhal/commit/7ad6b606886a9db0bd1c6501fc59fc8053a85802
