### ISSUE TITLE
Images are not displayed on the site

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal.com#422]
GitHub: https://github.com/sonarwhal/sonarwhal/tree/5277826d1dec02bccf55be1971af98ac40d0772b/packages/rule-meta-theme-color#why-is-this-important

Site: https://sonarwhal.com/docs/user-guide/rules/rule-meta-theme-color/#why-is-this-important

**Comment by sarvaje** [comment]
Is not just the images, the `why is this important section` is completely different :s

**Comment by sarvaje** [comment]
Orrrrr maybe I was watching a cached version of the documentation, because I can see the errors now :)

**Comment by sarvaje** [comment]
I'm going to take a look to this

**Comment by sarvaje** [comment]
This is now fixed. Closing!
