### ISSUE TITLE
`x` button from cookies banner is a bit off

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal.com#429]
e.g.:

Firefox:

![screen shot 2018-04-25 at 5 31 37 pm](https://user-images.githubusercontent.com/1223565/39252671-d534bfbe-48ae-11e8-8dd5-cbcd2f35a7e3.png)

Chrome:

![screen shot 2018-04-25 at 5 31 33 pm](https://user-images.githubusercontent.com/1223565/39252729-f8015b4c-48ae-11e8-98a7-3cca6ff5ea10.png)

**Comment by molant** [comment]
I might remove the circle entirely and call it a day.

**Comment by ststimac** [comment]
@molant sounds good to me.
