### ISSUE TITLE
Changelog section

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonarwhal.com#43]
@alrra I think this should come from [sonar](https://github.com/MicrosoftEdge/Sonar/) and should be calculated automatically between package version changes, tags, or any other way we seem appropriate. Thoughts?

@qzhou1607 your script should take it into account and put `changelog.md` in the right place.

**Comment by alrra** [comment]
> It could help us automate the creation of the changelog if we are strict(er) with the commit messages.

Fixed in https://github.com/sonarwhal/sonar/pull/373.
