### ISSUE TITLE
Mobile TOC subcategories are all lowercase

### ISSUE THREAD

**Issue by ststimac** [sonarwhal/sonarwhal.com#442]
![screen shot 2018-05-10 at 1 38 27 pm](https://user-images.githubusercontent.com/18073131/39893083-8b7b3e20-5457-11e8-9eca-3b1e4e8538e8.png)

Concepts, rules, further configuration should all start with a capital letter.

It's been a while so I'm not sure where the ToC is being pulled in from.

**Comment by ststimac** [comment]
Same thing under the contributor guide: 

![screen shot 2018-05-10 at 1 41 54 pm](https://user-images.githubusercontent.com/18073131/39893222-f09aaab6-5457-11e8-9379-fcf59d1df12d.png)

**Comment by molant** [comment]
Code is in [`sub-age.hbs`](https://github.com/sonarwhal/sonarwhal.com/blob/59b21956cd610a7b263420d8a2633bb88d84fd73/src/sonarwhal-theme/layout/partials/sub-page.hbs#L51). You can probably add a `capitalize` to `{{title}}` or `{{this}}` (or maybe both?) and that should fix it

**Comment by ststimac** [comment]
Edit: some other things seem to not be rendering correctly either so it may just be my machine. I am investigating.

**Comment by ststimac** [comment]
@molant I've got that weird thing happening when I run everything locally, the menu & some styles aren't rendering again. This was happening two months ago or so. It's happening on both machines with everything from the repo updated. 

Maybe next week you or @alrra can look at my machine? I'll be heads down on other work until then.

**Comment by molant** [comment]
@ststimac the latest version of the site should have the `watch` task working correctly thanks to @sarvaje

**Comment by ststimac** [comment]
@molant cool, thanks @sarvaje! 

I probably won't have time to start back up on this until next week. Some last minute things popped up for Jason & there are some smaller tasks I'd like to get out of the way.
