### ISSUE TITLE
https://sonarwhal.com/scanner/ returns 500 result

### ISSUE THREAD

**Issue by Simply007** [sonarwhal/sonarwhal.com#449]
Bug report:

 After accessing https://sonarwhal.com/scanner I am getting 500 http status error:
* The page cannot be displayed because an internal server error has occurred.

**General headers:**
Request URL: https://sonarwhal.com/scanner/
Request Method: GET
Status Code: 500 Internal Server Error
Remote Address: 52.184.193.104:443
Referrer Policy: no-referrer-when-downgrade
**Reposnse headers**
Content-Length: 75
Content-Type: text/html
Date: Tue, 29 May 2018 13:02:20 GMT
Strict-Transport-Security: max-age=31536000
Request URL: https://sonarwhal.com/scanner/
Request Method: GET
Status Code: 500 Internal Server Error
Remote Address: 52.184.193.104:443
Referrer Policy: no-referrer-when-downgrade
Content-Length: 75
Content-Type: text/html
Date: Tue, 29 May 2018 13:02:20 GMT
Strict-Transport-Security: max-age=31536000
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en,cs;q=0.9,en-US;q=0.8
Cache-Control: max-age=0
Connection: keep-alive
Cookie: consent=on; _ga=GA1.2.836500726.1527598158; _gid=GA1.2.1077847205.1527598158; _gat=1
Host: sonarwhal.com
Referer: https://sonarwhal.com/
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en,cs;q=0.9,en-US;q=0.8
Cache-Control: max-age=0
Connection: keep-alive
Cookie: consent=on; _ga=GA1.2.836500726.1527598158; _gid=GA1.2.1077847205.1527598158; _gat=1
Host: sonarwhal.com
Referer: https://sonarwhal.com/
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

**Comment by alrra** [comment]
@sarvaje ⬆️

**Comment by molant** [comment]
It looks like there's a problem with Azure. Some packages are not found and it fails to start. Trying to figure out why it broke and if it's in our side or Azure's side.

**Comment by molant** [comment]
This is fixed now. There was a problem with the configured node version and a missing dependency (`request`) that for whatever reason was installed automatically previously
