### ISSUE TITLE
Re-add Source Sans Pro

### ISSUE THREAD

**Issue by ststimac** [sonarwhal/sonarwhal.com#460]
Somehow the code for this font was deleted. Need to re-add it back to the website as the fallback Verdana is far too large in comparison to the headings that are all in Montserrat. 

Need to update Verdana to Arial.

**Comment by molant** [comment]
Now that you are looking into the fonts maybe it's a good time to review if we need all font weights for montserrat?

**Comment by ststimac** [comment]
Might be able to reduce to 2 from the 3 but I'm not sure. I will have to see which font weights are applied where.

**Comment by ststimac** [comment]
I mean down to 2 from 4.

**Comment by molant** [comment]
There are currently 4 weights: `200,300,400,500`
