### ISSUE TITLE
every time i use put url in sonarwhal i get this (Uh-oh! There's been an error and the scan could not start.)

### ISSUE THREAD

**Issue by waleader** [sonarwhal/sonarwhal.com#465]
every time i use put url in sonarwhal i get this (Uh-oh! There's been an error and the scan could not start.)

**Comment by alrra** [comment]
@sarvaje ⬆️

**Comment by molant** [comment]
@sarvaje has spent most of the day trying to get this working. The problem seems to be in the nginx machine that's completely unresponsive and doesn't respond to anything (not even school key resets from azure, restarts, etc.). The plan at the moment is to nuke it tomorrow and redeploy.

**Comment by sarvaje** [comment]
I tried yesterday to recover the previous machine, but it was impossible (I couldn't connect to the machine via ssh, even after restart it). Today I have created a regular vm with just ubuntu and I have installed docker manually and configured everything to have it working.

@waleader it should be working now, if you see the error again, please, reopen the issue and let me know. Thanks!!
