### ISSUE TITLE
Search results page

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonarwhal.com#80]
We need a search results page in case JS isn't enabled in the site.
@ststimac can you do the design, basic html and do a PR?
@qzhou1607 will do the backend part once I do #57 in that same branch before merging

**Comment by ststimac** [comment]
@qzhou1607 question about the search results page, right now there's a search.hbs file under partials, is that supposed to be the search results page? Just want to make sure before I start adding code to it. :)

**Comment by qzhou1607** [comment]
@ststimac This page was added by @molant . But from the look of it, I think it's safe to code the search result on it. Do we need another landing page for initiating the search? Or is all the search initiated from the search bar?

**Comment by ststimac** [comment]
@qzhou1607 the search is initiated from the search bar. Users will need to be able to hit 'enter' to initiate the search, this is most important on smaller screens as the search results preview won't be available. Let me know what we need to do to make that happen. I don't think that (hitting enter to search) works at the moment.

**Comment by qzhou1607** [comment]
Is this only for the small screen? Currently the result box pops up and changes content real time during typing, and hitting `enter` leads to the first page in the result. Do we still keep this behavior in bigger screens?
>Users will need to be able to hit 'enter' to initiate the search

**Comment by molant** [comment]
> Is this only for the small screen?

No, if users have JS disabled then they will land in this page too regardless of the screen size.
