### ISSUE TITLE
Make linking to subsections easier

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal.com#84]
It would be nice when hovering / tapping on a section title to show a `#` or an link icon , and by tapping / clicking on that, to link to that section.

E.g. from http://eslint.org/docs/rules/:

![](https://cloud.githubusercontent.com/assets/1223565/26348117/548695ee-3fb4-11e7-9303-3d013dc7d51f.gif)

**Comment by molant** [comment]
@ststimac maybe you want to do this as part of your current work of #128 
Note that this links should be for the sub titles and not the main one (opposite to what you are doing with edit/signal)
